//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKBNIDVerify.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.LoginUsers = new HashSet<LoginUser>();
        }
    
        public int id { get; set; }
        public string role_name { get; set; }
        public Nullable<int> role_priority { get; set; }
        public string role_description { get; set; }
    
        public virtual ICollection<LoginUser> LoginUsers { get; set; }
    }
}
