//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKBNIDVerify.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchLog
    {
        public int id { get; set; }
        public string NID { get; set; }
        public string DOB { get; set; }
        public string branchCode { get; set; }
        public string searchResponse { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public string createdBy { get; set; }
    }
}
